import type { Metadata } from "next";
import NavigationBar from "@/components/NavigationBar";
import "./globals.css";

export const metadata: Metadata = {
  title: "%s - Willem's Fizzy Logic",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="flex h-full w-full">
      <body className="flex h-full w-full bg-zinc-100">
        <div className="fixed flex h-full w-full">
          <div className="mx-auto h-full w-full bg-white lg:max-w-5xl"></div>
        </div>
        <div className="relative mx-auto w-full px-8 lg:max-w-5xl lg:px-12">
          <header>
            <NavigationBar />
          </header>
          <main>{children}</main>
        </div>
      </body>
    </html>
  );
}
